### ISSUE TITLE
상품 상세 페이지 구현 

### ISSUE THREAD

**Issue by ywoo21** [ywoo21/Boogle-Web#10]
![image](https://user-images.githubusercontent.com/23696493/72684229-2130e200-3b22-11ea-851d-095ca292c601.png)

**Comment by ywoo21** [comment]
아직 API 구현까지는 못했는데 다음과 같이 sell_item 도큐먼트가 구성됩니다!

**Comment by ywoo21** [comment]
## 상품 상세 조회

### http://13.125.191.60:8080/sell?id={id}

| 메소드 | 경로                 | 짧은 설명 |
| ------ | -------------------- | --------- |
| GET    | /sell/detail?id={id} |           |

### 요청 헤더

```
Content-Type : application/json,
```

### 요청 파라미터

| 파라미터 명 | 파라미터 값 예시           |
| ----------- | -------------------------- |
| id          | "5e26e2e83eb3ee91a8915ecf" |

### 요청 

### 응답 바디

#### 판매 상품 상세 조회 성공

```
{
    "status": 200,
    "message": "판매 상품 상세 조회 성공",
    "data": {
        "_id": "5e26e2e83eb3ee91a8915ecf",
        "itemId": "9788962184181",
        "title": "맨큐의 경제학",
        "author": "그레고리 맨큐",
        "publisher": "한티에듀",
        "pubdate": "201803",
        "imageUrl": "https://bookthumb-phinf.pstatic.net/cover/139/212/13921278.jpg?type=m1&udate=20181224",
        "price": "42000",
        "regiPrice": "10000",
        "regiImageUrlList": [
            "https://s3.ap-northeast-2.amazonaws.com/boogle.shop/df9c9f42c81747b890b706c100e3e0f3.png"
        ],
        "dealType": 0,
        "qualityIn": [
            false,
            true,
            false,
            true,
            false,
            false
        ],
        "qualityOut": [
            true,
            false,
            false,
            false,
            true
        ],
        "sellerId": 0,
        "regiTime": "2020-01-21T11:39:19.435+0000",
        "comment": "상태 양호합니다."
    }
}
```

#### 판매 상품 상세 조회 실패

```
{
    "status": 404,
    "message": "판매 상품 상세 조회 실패"
}
```

**Comment by wakii** [comment]
id 는 어떤 방식으로 얻게 되나요??

**Comment by ywoo21** [comment]
상세 페이지 이전 단계인 판매 상품 리스트 뷰를 띄울때 해당 상품에 대한 정보를 프론트엔드에서 상태로 저장하고 있을 것입니다! 그것을 활용해서(해당 상품 이미지를 클릭했을때 상세로 넘어가면 id를 넘겨줘야 겠죠!) 파라미터로 id로 넘어가게 됩니다! 설명을 잘 못한거 같은데 이따가 행아웃에서 자세하게 알려드리겠습니다.

**Comment by ywoo21** [comment]
![image](https://user-images.githubusercontent.com/23696493/72975030-6e0f0400-3e13-11ea-8ff9-b1890f7de2f6.png)

**Comment by ywoo21** [comment]
## 글 작성

| 메소드 | 경로         | 짧은 설명      |
| ------ | ------------ | -------------- |
| POST   | /transaction | 거래 정보 저장 |

### 요청 헤더

```
Authorization: token
```

### 요청 바디

- sellItemId : sell_item 고유 번호
- sellerId : seller 고유 번호
- transactionType : 거래 방식(0 : 직거래 , 1 : 북을박스 거래)
- sellerStep, buyerStep은 0으로 설정
- boxId, boxPassword는 ""으로 설정

```
{
    "sellItemId" : "5e2d0c1d3eb3eeed8c6d89cc",
    "sellerId" : 20,
    "transactionType" : 0,
    "sellerStep" : 0 ,
    "buyerStep" : 0,
    "boxId" : "",
    "boxPassword" : ""
}
```

### 응답 바디

#### 거래 정보 저장 성공

```
{
    "status": 201,
    "message": "거래 정보 저장 성공"
}
```

#### 거래 정보 저장 실패

```
{
    "status": 600,
    "message": "거래 정보 저장 실패",
    "data": null
}
```

**Comment by ywoo21** [comment]
{
    "status": 200,
    "message": "판매 상품 상세 조회 성공",
    "data": {
        "sellItem": {
            "_id": "5e2d39aa3eb3ee04d828414d",
            "itemId": "9788993995015",
            "title": "맨큐의 경제학",
            "author": "그레고리 맨큐",
            "publisher": "교보문고",
            "pubdate": "201208",
            "imageUrl": "https://bookthumb-phinf.pstatic.net/cover/060/576/06057655.jpg?type=m1&udate=20130126",
            "price": "35000",
            "regiPrice": "12000",
            "regiImageUrlList": [
                "https://s3.ap-northeast-2.amazonaws.com/boogle.shop/15bbe10475c84f75850ec62ab3c55e04.png"
            ],
            "dealType": 0,
            "qualityIn": [
                false,
                true,
                false,
                false,
                false,
                false
            ],
            "qualityOut": [
                true,
                false,
                false,
                false,
                false
            ],
            "sellerId": 7,
            "regiTime": "2020-01-26T07:03:03.692+0000",
            "comment": "상태 양호합니다."
        },
        "sellerUser": {
            "id": 7,
            "email": "admin@boogle.shop",
            "password": "",
            "checkList": "110",
            "name": "북을",
            "nickname": "북을",
            "campus": "서강대학교",
            "semester": "1",
            "major": "경영학과",
            "phoneNumber": "01012345678"
        }
    }
}
