### ISSUE TITLE
Cross Origin Issue

### ISSUE THREAD

**Issue by wakii** [ywoo21/Boogle-Web#15]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/17175936/72818630-25d6d100-3caf-11ea-9c33-9700e756ab46.png">

useEffect 함수 내에 비동기처리를 하여 item data를 가져오려는데 cross-origin-issue가 뜹니다.

**Comment by wakii** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/17175936/72818773-5f0f4100-3caf-11ea-9ae4-701cfea7da6f.png">


postman 내에서 다음과 같이 요청했을 때 아래와 같이 나오는데 이도 corss-origin-issue인가요??

**Comment by ywoo21** [comment]
http://13.125.191.60:8080/sell/detail?id=5e26e2e83eb3ee91a8915ecf

**Comment by wakii** [comment]
1. postman에서의 요청은 성공적으로 나옵니다.

2. cross-origin-issue는 localhost 상에서 그대로 입니다.

**Comment by ywoo21** [comment]
axios 코드 한번 올려주세요!

**Comment by wakii** [comment]
import React, { useState, useEffect } from "react";
// import styled from "styled-components";
import { Col, Row, Carousel, Icon } from "antd";
import { Link } from "react-router-dom";
import axios from "axios";

export default function Subject() {
  const { id, setId } = useState("5e26e2e83eb3ee91a8915ecf");
  const { item, setItem } = useState({});
  const detail_sub_url = `http://13.125.191.60:8080/sell?id={id}`;
  // console.log(detail_sub_url);

  useEffect(() => {
    const getItemData = async () => {
      const result = await axios.get(detail_sub_url);
      setItem(result.data);
      console.log(1010);
    };
    getItemData();
  }, []);

  return (
    <div>

**Comment by wakii** [comment]
해결됐습니당 ㅎㅎ

**Comment by wakii** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/17175936/72873349-ebaf1300-3d32-11ea-82ed-49aca13ec6d6.png">


<img width="436" alt="image" src="https://user-images.githubusercontent.com/17175936/72873364-fb2e5c00-3d32-11ea-8148-92cae3a317df.png">
에서 item regiImageUrl list를 접근하려고 하는데 처음에 가져오는 값이 undefined라 그런지 에러가 나네요.
이런 경우, 에러 처리만 해주면 되는 걸까요??

**Comment by ywoo21** [comment]
react component가 어떤식으로 렌더링 되는지를 생각해보면, 최초 렌더링 시점에서는 http통신이 일어나지 않기 때문에 imgUrl이 undefined가 될것입니다. 그렇기 때문에, 통신이 이루어지고 imgUrl에 값이 들어갔을 때 해당 컴포넌트가 재렌더링 되도록 해야되겠죠!
