### ISSUE TITLE
로그인 API

### ISSUE THREAD

**Issue by ywoo21** [ywoo21/Boogle-Web#7]
### http://13.125.191.60:8080/users/signin

| 메소드 | 경로          | 짧은 설명 |
| ------ | ------------- | --------- |
| POST    | /users/signin |           |

### 요청 헤더

```
Content-Type : application/json,
```

### 요청 바디

```
{
	"email" : "admin@boogle.shop",
	"password" : "boogleadmin"
}
```

#### 로그인 성공

```
{
    "status": 200,
    "message": "로그인 성공",
    "data": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJib29nbGUiLCJ1c2VyX2lkeCI6NywiZXhwIjoxNTgxNjAzNTQ1fQ.ifAvMMvlKv9dbcc38_uVKN1tPjfxekN3Jsu4r7hvchU"
}
```

#### 아이디 또는 비빌번호가 틀렸을 때

```
{
    "status": 404,
    "message": "로그인 실패 "
}
```

**Comment by wakii** [comment]
@ywoo21 
api 주소에 signup 으로 되어있는데 그대로 쓰면 되나요?
요청 헤더에는 signin으로 되어있네요

**Comment by ywoo21** [comment]
@wakii 
오타입니다! signin 맞습니다!

**Comment by ywoo21** [comment]
@wakii 메소드도 GET이 아니라 POST입니다.
